[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/blog"
  to = "/blog/_site/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/_site/:splat"
  status = 200